[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "forge-std/=dependencies/forge-std-1.9.7/src",
]

[dependencies]
forge-std = "1.9.7"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
